import type { MenuItem } from './menuTypes.ts';

/**
 * Categorias exibidas no cardápio (abas fixas). A categoria original de cada
 * item foi preservada em `subcategory` (ex.: "Combos para 2 Pessoas!").
 * Categorias sem itens (ex.: Sobremesas, ainda sem produtos avulsos) não
 * aparecem na interface.
 */
export const CATEGORIES = [
  'Destaques',
  'Hambúrgueres',
  'Combos',
  'Acompanhamentos',
  'Bebidas',
  'Sobremesas',
] as const;

export type MenuCategory = (typeof CATEGORIES)[number];

export const MENU_ITEMS: MenuItem[] = [
  // Destaques
  {
    id: 'destaque-1',
    name: 'Burger 120g Bacon & Cheddar Cristovão Bacon',
    category: 'Destaques',
    subcategory: 'Destaques',
    description: 'Pão brioche, Hamburguer 120gr, Bacon crocante, Queijo Cheddar derretido, Alface Americana fresca, Tomate e Maionese Da Casa artesanal.',
    price: 48.90,
    originalPrice: 59.90,
    image: 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?auto=format&fit=crop&w=800&q=80',
    serves: 'Serve 1 pessoa',
    highlight: true,
    tags: ['Mais Vendido', 'Oferta'],
    isAvailable: true,
  },
  {
    id: 'destaque-2',
    name: 'Cristovão Turbo Pickles',
    category: 'Destaques',
    subcategory: 'Destaques',
    description: 'Pão + Hamburguer + Cheddar + Bacon + Muito Pickles Americano crocante + Ketchup Heinz + Mostarda Heinz + Maionese Caseira.',
    price: 51.90,
    originalPrice: 59.90,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80',
    serves: 'Serve 1 pessoa',
    highlight: true,
    tags: ['Queridinho', 'Pickles Lovers'],
    isAvailable: true,
  },
  {
    id: 'destaque-3',
    name: 'Combo: Cristovão Calabresa + Fritas + Coca Cola 200 ml',
    category: 'Combos',
    subcategory: 'Destaques',
    description: 'Dois Burger 120gr no pão macio, com Cheddar derretido, Calabresa fatiada na chapa, Alface, Tomate, Cebola Caramelizada e Maionese da casa. Acompanha fritas palito crocantes e Coca-Cola 200ml gelada.',
    price: 65.90,
    originalPrice: 75.90,
    image: 'https://images.unsplash.com/photo-1594212699903-eca8a3a114f1?auto=format&fit=crop&w=800&q=80',
    serves: 'Serve 1 pessoa',
    highlight: true,
    tags: ['Combo Completo', 'Super Promoção'],
    isAvailable: true,
  },
  {
    id: 'destaque-4',
    name: 'Burger Duplo & Onion Rings - Cristóvão Onions',
    category: 'Destaques',
    subcategory: 'Destaques',
    description: 'Dois Burgers de 120g com crosta smash, Cheddar derretido, Bacon e Anéis de Cebola Onion Rings crocantes, no Pão Macio com Alface, Tomate e Maionese da Casa.',
    price: 52.90,
    originalPrice: 59.90,
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=800&q=80',
    serves: 'Serve 1 pessoa',
    highlight: true,
    tags: ['Crocante', 'Duplo Smash'],
    isAvailable: true,
  },

  // Baratíssimos do São Cristóvão
  {
    id: 'baratissimo-1',
    name: 'Burger Classic',
    category: 'Hambúrgueres',
    subcategory: 'Baratíssimos do São Cristóvão',
    description: 'Pão brioche dourado, Burger 120g com Blend Especial suculento, Cheddar derretido, Alface Americana e Maionese Caseira da casa.',
    price: 28.90,
    originalPrice: 29.90,
    image: 'https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?auto=format&fit=crop&w=800&q=80',
    serves: 'Serve 1 pessoa',
    tags: ['Econômico', 'Clássico'],
    isAvailable: true,
  },

  // Aproveite - Por tempo limitado!
  {
    id: 'limitado-1',
    name: 'Burger Gouda - Edição Especial',
    category: 'Destaques',
    subcategory: 'Aproveite - Por tempo limitado!',
    description: 'Pão brioche selado na manteiga, Hamburguer Angus 120 gr, Cheddar derretido, Bacon crocante, generoso Queijo Gouda Empanado e frito na hora com Maionese da Casa.',
    price: 49.90,
    image: 'https://images.unsplash.com/photo-1607013251379-e6eecfffe234?auto=format&fit=crop&w=800&q=80',
    serves: 'Serve 1 pessoa',
    tags: ['Edição Especial', 'Gouda Empanado', 'Limitado'],
    isAvailable: true,
  },

  // Os Queridos do São Cristóvão
  {
    id: 'queridos-1',
    name: 'Burguer Junior 120 gr - Pão Carne e Queijo',
    category: 'Hambúrgueres',
    subcategory: 'Os Queridos do São Cristóvão',
    description: 'Perfeito para quem tem pouca fome ou para as crianças. Pão brioche macio com hambúrguer bovino de 100g feito com carne selecionada e cheddar derretido na medida certa. Simples, saboroso e no tamanho ideal. (Obs.: servido sem maionese).',
    price: 33.90,
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80',
    serves: 'Serve 1 pessoa',
    tags: ['Kids & Leve', 'Pão Carne e Queijo'],
    isAvailable: true,
  },
  {
    id: 'queridos-2',
    name: 'Burguer Duplo + Costela - Cristovão Angus Perfeito',
    category: 'Hambúrgueres',
    subcategory: 'Os Queridos do São Cristóvão',
    description: 'Dois hambúrgueres Angus 120g, com costela bovina desfiada suculenta, cheddar derretido e bacon crocante, no pão macio com alface, cebola roxa e maionese da casa. Um burguer robusto e intenso.',
    price: 56.90,
    image: 'https://images.unsplash.com/photo-1596662951482-0c4ba74a6df6?auto=format&fit=crop&w=800&q=80',
    serves: 'Serve 1 pessoa',
    tags: ['Costela Desfiada', 'Robusto Angus'],
    isAvailable: true,
  },
  {
    id: 'queridos-3',
    name: 'Combo: Cristóvão Angus Perfeito + Fritas + Coca 200 ml',
    category: 'Combos',
    subcategory: 'Os Queridos do São Cristóvão',
    description: 'Burger Angus com Costela Desfiada, Cheddar, Bacon Crocante e Maionese da Casa. Acompanha Batata Frita palito sequinha e Coca-Cola 200 ml gelada. Um combo completo e cheio de sabor.',
    price: 65.90,
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=800&q=80',
    serves: 'Serve 1 pessoa',
    tags: ['Combo Angus', 'Mais Pedido'],
    isAvailable: true,
  },


  // Combo Individual
  {
    id: 'combo-ind-1',
    name: 'Combo: Cristovão Bacon + Fritas + Coca 200 ml',
    category: 'Combos',
    subcategory: 'Combo Individual',
    description: 'Pão brioche, Smash Burger 120gr + Bacon crocante + Tomate + Alface e Maionese da Casa + 1 Batata Frita palito crocante + 1 Coca 200ml gelada.',
    price: 52.90,
    image: 'https://images.unsplash.com/photo-1594212699903-eca8a3a114f1?auto=format&fit=crop&w=800&q=80',
    serves: 'Serve 1 pessoa',
    tags: ['Individual Favorito'],
    isAvailable: true,
  },
  {
    id: 'combo-ind-2',
    name: 'Combo: Cristóvão Onions + Fritas + Coca 200 ml',
    category: 'Combos',
    subcategory: 'Combo Individual',
    description: '2 Burgers de 120 gr, Cheddar, Bacon Crocante e Cebola Frita Dourada, no Pão Macio e Maionese da Casa. Acompanha Batata Palito e Coca-Cola 200ml gelada. Um combo forte, completo e feito pra matar a fome!',
    price: 58.90,
    image: 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?auto=format&fit=crop&w=800&q=80',
    serves: 'Serve 1 pessoa',
    tags: ['Cebola Dourada', 'Mata a Fome'],
    isAvailable: true,
  },
  {
    id: 'combo-ind-3',
    name: 'Combo: Cristovão Triplo + Fritas + Coca 200 ml',
    category: 'Combos',
    subcategory: 'Combo Individual',
    description: 'Burger triplo Angus 360g de pura carne, Pão brioche, Cheddar derretido abundante e maionese da casa. Acompanha Batata Palito e Coca-Cola 200ml gelada.',
    price: 60.90,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80',
    serves: 'Serve 1 pessoa',
    tags: ['360g Carne', 'Triplo Angus'],
    isAvailable: true,
  },
  {
    id: 'combo-ind-4',
    name: 'Combo: Big Cristovão + Fritas + Coca Cola 200ml',
    category: 'Combos',
    subcategory: 'Combo Individual',
    description: '2x Burger Angus de 120 gr no Pão Macio, Cheddar, Bacon Crocante e Cebola Caramelizada caseira. Finalizado com Alface, Tomate e Maionese da Casa. Acompanha Batata Frita e Coca-Cola 200ml gelada.',
    price: 62.40,
    originalPrice: 64.90,
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=800&q=80',
    serves: 'Serve 1 pessoa',
    tags: ['Cebola Caramelizada', 'Oferta'],
    isAvailable: true,
  },

  // Combos para 2 Pessoas!
  {
    id: 'combo-casal-1',
    name: 'Combo: 2 Burgers (Big + Classic) + Fritas + 2 Coca-Cola 200ml',
    category: 'Combos',
    subcategory: 'Combos para 2 Pessoas!',
    description: 'Inclui 1 Burger Big (duplo com Bacon e Cebola caramelizada) e 1 Burger Classic (Pão, Burger, Alface e Maionese). Acompanha Batata Palito crocante e 2 Coca-Cola 200ml geladas.',
    price: 80.40,
    originalPrice: 84.90,
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80',
    serves: 'Serve 2 pessoas',
    tags: ['Combo Casal', 'Mais Econômico'],
    isAvailable: true,
  },
  {
    id: 'combo-casal-2',
    name: 'Combo: 2x Burger 120g com Costela Desfiada + 1 Fritas + 2x Coca Cola 200 ml',
    category: 'Combos',
    subcategory: 'Combos para 2 Pessoas!',
    description: 'Nosso Combo é composto por 2 lanches com burguer de 120 gr (cada), Costela Desfiada suculenta, Cheddar derretido, Bacon, Alface e Cebola. Uma porção de Batata Frita e 2 un de Coca Cola 200 ml Geladinha!',
    price: 87.40,
    originalPrice: 89.90,
    image: 'https://images.unsplash.com/photo-1596662951482-0c4ba74a6df6?auto=format&fit=crop&w=800&q=80',
    serves: 'Serve 2 pessoas',
    tags: ['Costela Casal', 'Especial'],
    isAvailable: true,
  },
  {
    id: 'combo-casal-3',
    name: 'Combo: 2x Cristovão Bacon + 1 Fritas + 2x Coca Cola 200 ml',
    category: 'Combos',
    subcategory: 'Combos para 2 Pessoas!',
    description: '2x Cristovão Bacon no Pão Brioche, Burger de 120gr, Bacon Crocante, Alface, Tomate e a nossa Maionese Caseira! Acompanha uma porção de Batata Frita e 2 und de Coca Cola 200 ml geladinha!',
    price: 86.40,
    originalPrice: 89.90,
    image: 'https://images.unsplash.com/photo-1553979459-d2229ba7433b?auto=format&fit=crop&w=800&q=80',
    serves: 'Serve 2 pessoas',
    tags: ['Dupla de Bacon', 'Best Seller'],
    isAvailable: true,
  },

  // Box Experiência
  {
    id: 'box-1',
    name: 'Box Experiência Individual',
    category: 'Combos',
    subcategory: 'Box Experiência',
    description: '1 Pão Classic com Hambúrguer Angus De 120gr e Queijo + 1 Burger Doce Pão com Nutella e Kinder Bueno + 1 Fritas Palito com Cheddar Cremoso e Farofinha de Bacon + 3 Molhos especiais da casa.',
    price: 109.90,
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=800&q=80',
    serves: 'Serve 1 pessoa',
    tags: ['Experiência Completa', 'Com Doce Nutella'],
    isAvailable: true,
  },
  {
    id: 'box-2',
    name: 'Box Experiência Casal',
    category: 'Combos',
    subcategory: 'Box Experiência',
    description: '1 Pão Classic com Hambúrguer Angus 120 gr e Queijo Cheddar + 1 Pão com Hambúrguer Angus 120 gr, Cheddar, Bacon e Maionese da Casa + 1 Fritas Palito com Cheddar e Farofinha de Bacon + 3 Molhos da Casa.',
    price: 109.90,
    image: 'https://images.unsplash.com/photo-1594212699903-eca8a3a114f1?auto=format&fit=crop&w=800&q=80',
    serves: 'Serve 2 pessoas',
    tags: ['Box Casal Premium', '3 Molhos'],
    isAvailable: true,
  },
  {
    id: 'box-3',
    name: 'Combo Experiência',
    category: 'Combos',
    subcategory: 'Box Experiência',
    description: 'Combo com 3 Burguers (Junior + Burguer c/ Cebola Caramelizada + Burguer Bacon) + 1 porção de Onion Rings crocantes + 1 Porção de Batata com Cheddar e Bacon + 4un de Coxinha de Frango ou Bolinha de Queijo + 1 Pote Max Maionese Caseira.',
    price: 139.90,
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80',
    serves: 'Serve 3 pessoas',
    tags: ['Trio Fartura', 'Salgadinhos Inclusos'],
    isAvailable: true,
  },
  {
    id: 'box-4',
    name: 'Combo Box Experiencia Nutella Com Kinder Bueno',
    category: 'Combos',
    subcategory: 'Box Experiência',
    description: '1 Burger Junior + 1 Burger Bacon + 1 Burger Especial Nutella Com Kinder Bueno + 1 porção de onions crocantes + 1 porção de batata com cheddar e farofa de bacon + 4un de Coxinha ou Bolinha de Queijo + 1 Max Maionese Caseira.',
    price: 139.90,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80',
    serves: 'Serve 3 pessoas',
    tags: ['Experiência Suprema', 'Com Kinder Bueno'],
    isAvailable: true,
  },

  // Campeões em vendas
  {
    id: 'campeoes-1',
    name: '2x Un. Burger Classic - Pequenas Fomes (Sem Fritas, Sem Bebida)',
    category: 'Combos',
    subcategory: 'Campeões em vendas',
    description: 'Oferta imperdível para os amantes de hambúrguer. Pão brioche dourado, suculenta carne de 100gr com cheddar derretido, camada de alface americana fresca e maionese caseira.',
    price: 68.90,
    originalPrice: 69.90,
    image: 'https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?auto=format&fit=crop&w=800&q=80',
    serves: 'Serve 2 pessoas',
    tags: ['Campeão', 'Pequenas Fomes'],
    isAvailable: true,
  },
  {
    id: 'campeoes-2',
    name: '2x Lanches - Hamburguer + Costela Desfiada + 1 Fritas + 2 Coquinhas',
    category: 'Combos',
    subcategory: 'Campeões em vendas',
    description: 'Dois deliciosos hambúrgueres de 120gr cada acompanhados de suculenta costela desfiada (80gr), queijo cheddar derretido, bacon crocante, alface americana fresca, fritas e duas coquinhas geladas.',
    price: 86.90,
    originalPrice: 89.90,
    image: 'https://images.unsplash.com/photo-1596662951482-0c4ba74a6df6?auto=format&fit=crop&w=800&q=80',
    tags: ['Mais Pedido em Oferta', 'Costela Desfiada'],
    isAvailable: true,
  },
  {
    id: 'campeoes-3',
    name: 'Burger Junior (Kids)',
    category: 'Hambúrgueres',
    subcategory: 'Campeões em vendas',
    description: 'Projetado para crianças e apetites moderados. Pão brioche fresco, hambúrguer de 100g de carne de alta qualidade, generosa camada de cheddar derretido (servido sem maionese).',
    price: 33.90,
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80',
    serves: 'Serve 1 pessoa',
    tags: ['Kids', '100% Carne Bovina'],
    isAvailable: true,
  },
  {
    id: 'campeoes-4',
    name: 'Combinho pequeno - 1 classic + 1 fritas palito + 1 coquinha',
    category: 'Combos',
    subcategory: 'Campeões em vendas',
    description: 'Perfeito para pequenas fomes com muito sabor: 1 Classic (100g, cheddar, alface e maionese da casa) + 1 porção de fritas palito douradas + 1 coquinha gelada.',
    price: 54.90,
    image: 'https://images.unsplash.com/photo-1594212699903-eca8a3a114f1?auto=format&fit=crop&w=800&q=80',
    tags: ['Combinho Econômico'],
    isAvailable: true,
  },
  {
    id: 'campeoes-5',
    name: 'Mega Combo - 2 Big Cristovão - Sem Bebida E Sem Fritas',
    category: 'Combos',
    subcategory: 'Campeões em vendas',
    description: '2 unidades do Burger Big Cristovão: 2x Carnes De 100gr + Queijo Cheddar + Cebola Caramelizada + Bacon + Tomate + Alface E Maionese Caseira.',
    price: 82.90,
    originalPrice: 84.90,
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=800&q=80',
    tags: ['Mega Combo', '4 Carnes Total'],
    isAvailable: true,
  },
  {
    id: 'campeoes-6',
    name: 'Combo Família - 3 Lanches (1 Angus + 1 Bacon + 1 Junior) 2 Cocas 1 Suco Delvale',
    category: 'Combos',
    subcategory: 'Campeões em vendas',
    description: '1 Cristovão Angus Perfeito (160g, costela desfiada, bacon, cheddar, cebola roxa) + 1 Cristovão Bacon (120g, bacon, cheddar, alface, tomate) + 1 Cristovão Junior (carne e queijo) + 2 Coca 200ml + 1 Suco Del Valle Uva.',
    price: 102.90,
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=800&q=80',
    serves: 'Serve 3 pessoas',
    tags: ['Combo Família', 'Super Completo'],
    isAvailable: true,
  },

  // Nossos Burger`s
  {
    id: 'nossos-1',
    name: 'Big Cristovão',
    category: 'Hambúrgueres',
    subcategory: 'Nossos Burger`s',
    description: 'Pão brioche, 2 Hamburgueres Angus 120gr Cada (240g carne), Bacon crocante, Queijo Cheddar, Cebola Caramelizada, Alface Americana, Tomate e Maionese Da Casa.',
    price: 59.90,
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=800&q=80',
    serves: 'Serve 1 pessoa',
    tags: ['Double Angus 240g'],
    isAvailable: true,
  },
  {
    id: 'nossos-2',
    name: 'Cristovão Angus Perfeito (Costela)',
    category: 'Hambúrgueres',
    subcategory: 'Nossos Burger`s',
    description: 'Pão, 2x Hamburguer Angus 100gr, generosa porção de Costela Desfiada, Bacon crocante, Queijo Cheddar, Alface Americana, Cebola Roxa e Maionese Da Casa.',
    price: 59.90,
    image: 'https://images.unsplash.com/photo-1596662951482-0c4ba74a6df6?auto=format&fit=crop&w=800&q=80',
    serves: 'Serve 1 pessoa',
    tags: ['Costela Angus'],
    isAvailable: true,
  },
  {
    id: 'nossos-3',
    name: 'Cristovão Calabresa',
    category: 'Hambúrgueres',
    subcategory: 'Nossos Burger`s',
    description: 'Dois Burger 120gr no pão macio, com Cheddar derretido, fatias de Calabresa douradas, Alface, Tomate, Cebola Caramelizada e Maionese da casa.',
    price: 55.90,
    originalPrice: 56.90,
    image: 'https://images.unsplash.com/photo-1594212699903-eca8a3a114f1?auto=format&fit=crop&w=800&q=80',
    serves: 'Serve 1 pessoa',
    tags: ['Calabresa Especial'],
    isAvailable: true,
  },
  {
    id: 'nossos-4',
    name: 'Cristovão cremoso',
    category: 'Hambúrgueres',
    subcategory: 'Nossos Burger`s',
    description: 'Pão brioche, 2 Hambúrgueres Angus 100 gr cada, Bastante Cheddar Cremoso derretido em banho de queijo e Cebola Caramelizada.',
    price: 52.90,
    originalPrice: 56.90,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=800&q=80',
    serves: 'Serve 1 pessoa',
    tags: ['Super Cheddar', 'Cremoso'],
    isAvailable: true,
  },

  // Molhos
  {
    id: 'molho-1',
    name: 'Maionese Extra Caseira (Branca)',
    category: 'Acompanhamentos',
    subcategory: 'Molhos',
    description: 'Nossa famosa maionese branca secreta batida diariamente com ervas frescas e toque cítrico especial da casa. Potinho 60ml.',
    price: 4.00,
    image: 'https://images.unsplash.com/photo-1577906096429-f73c2c312435?auto=format&fit=crop&w=800&q=80',
    tags: ['Receita da Casa', 'Artesanal'],
    isAvailable: true,
  },
  {
    id: 'molho-2',
    name: 'Ketchup Heiz Original (Potinho)',
    category: 'Acompanhamentos',
    subcategory: 'Molhos',
    description: 'Potinho individual de Ketchup Heinz Original 60ml.',
    price: 4.00,
    image: 'https://images.unsplash.com/photo-1582878826629-29b7ad1cdc43?auto=format&fit=crop&w=800&q=80',
    tags: ['Heinz'],
    isAvailable: true,
  },
  {
    id: 'molho-3',
    name: 'Mostarda Heiz Original (Potinho)',
    category: 'Acompanhamentos',
    subcategory: 'Molhos',
    description: 'Potinho individual com Mostarda Heinz Original 60ml.',
    price: 4.00,
    image: 'https://images.unsplash.com/photo-1528751014936-863e6e7a319c?auto=format&fit=crop&w=800&q=80',
    tags: ['Heinz'],
    isAvailable: true,
  },

  // Bebidas
  {
    id: 'bebida-1',
    name: 'Coca-Cola Original 200ml',
    category: 'Bebidas',
    subcategory: 'Bebidas',
    description: 'Garrafinha 200ml trincando de gelada.',
    price: 5.90,
    image: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?auto=format&fit=crop&w=800&q=80',
    tags: ['Geladinha'],
    isAvailable: true,
  },
  {
    id: 'bebida-2',
    name: 'Refrigerante Guaraná Antarctica Lata 350ml',
    category: 'Bebidas',
    subcategory: 'Bebidas',
    description: 'Lata 350ml super gelada do tradicional guaraná do Brasil.',
    price: 6.90,
    image: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=800&q=80',
    tags: ['Lata 350ml'],
    isAvailable: true,
  },
  {
    id: 'bebida-3',
    name: 'Suco Del Valle Pêssego 290ml',
    category: 'Bebidas',
    subcategory: 'Bebidas',
    description: 'Lata 290ml gelada de suco de néctar de pêssego Del Valle.',
    price: 7.90,
    image: 'https://images.unsplash.com/photo-1613478223719-2ab802602423?auto=format&fit=crop&w=800&q=80',
    tags: ['Suco'],
    isAvailable: true,
  },
  {
    id: 'bebida-4',
    name: 'Budweiser Ow 330ml',
    category: 'Bebidas',
    subcategory: 'Bebidas',
    description: 'Cerveja Budweiser garrafa 330ml geladinha. Produto para maiores de 18 anos.',
    price: 12.90,
    image: 'https://images.unsplash.com/photo-1608270586620-248524c67de9?auto=format&fit=crop&w=800&q=80',
    tags: ['+18', 'Cerveja'],
    isAvailable: true,
  },
  {
    id: 'bebida-5',
    name: 'Heineken Long Neck 330ml',
    category: 'Bebidas',
    subcategory: 'Bebidas',
    description: 'Cerveja Heineken Premium Quality 330ml geladíssima. Produto para maiores de 18 anos.',
    price: 14.90,
    image: 'https://images.unsplash.com/photo-1618886614638-80e3c15cd819?auto=format&fit=crop&w=800&q=80',
    tags: ['+18', 'Puro Malte'],
    isAvailable: true,
  },
];
